src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_public;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getDate()
    {
        return $this->date;
    }

    public function setDate($date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('subtitle')
            ->add('content')
            ->add('is_public')
            ->add('date')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/article-table", name="article_table", methods={"GET"})
     */
    public function articlesTable(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/table.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN", message="[Accès restreint] - Vous n'avez pas le droit de faire cette action. Veuillez retourner en arrière.")
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_table');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_table');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger mb-2">Supprimer</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success my-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article - Édition{% endblock %}

{% block body %}
{% include "navbar.html.twig" %}
<h1 class="text-center">Éditer l'article {{article.id}}</h1>

<div class="container">
  {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}
  {{ include('article/_delete_form.html.twig') }}

  <a class="btn btn-primary" href="{{ path('article_table') }}">< Retour aux articles</a>

</div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
{% include "navbar.html.twig" %}
<div class="container">
  <h1 class="text-center">Article index</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Subtitle</th>
        <th>Content</th>
        <th>Is_public</th>
        <th>Date</th>
        <th>Image</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
        <td>{{ article.id }}</td>
        <td>{{ article.title }}</td>
        <td>{{ article.subtitle }}</td>
        <td>{{ article.content }}</td>
        <td>{{ article.isPublic ? 'Yes' : 'No' }}</td>
        <td>{{ article.date ? article.date|date('Y-m-d') : '' }}</td>
        <td>{{ article.image }}</td>
        <td>
          <a class="btn btn-primary mb-1" href="{{ path('article_show', {'id': article.id}) }}">show</a>
          <a class="btn btn-warning" href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
        </td>
      </tr>
      {% else %}
      <tr>
        <td colspan="8">no records found</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <a class="btn btn-success" href="{{ path('article_new') }}">Create new</a>
</div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
{% include "navbar.html.twig" %}
<div class="container">
  <h1 class="text-center">Poster un article</h1>

  <a class="btn btn-primary mb-5" href="{{ path('default') }}">< Page d'accueil</a>
  {{ include('article/_form.html.twig') }}

  <a class="btn btn-primary" href="{{ path('article_table') }}">Retour a la liste</a>
</div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
{% include "navbar.html.twig" %}

<h1 class="text-center mt-3">Supprimer l'article {{article.id}} ?</h1>

<div class="container">
  <table class="table">
    <tbody>
      <tr>
        <th>Id</th>
        <td>{{ article.id }}</td>
      </tr>
      <tr>
        <th>Title</th>
        <td>{{ article.title }}</td>
      </tr>
      <tr>
        <th>Subtitle</th>
        <td>{{ article.subtitle }}</td>
      </tr>
      <tr>
        <th>Content</th>
        <td>{{ article.content }}</td>
      </tr>
      <tr>
        <th>Is_public</th>
        <td>{{ article.isPublic ? 'Yes' : 'No' }}</td>
      </tr>
      <tr>
        <th>Date</th>
        <td>{{ article.date ? article.date|date('Y-m-d') : '' }}</td>
      </tr>
      <tr>
        <th>Image</th>
        <td><img style="max-width:35vh;" src="{{article.image ? article.image : "https://media.discordapp.net/attachments/814250385190420483/833634824140095498/no_preview.png?width=1157&height=651"}}" alt="Image"></td>
      </tr>
    </tbody>
  </table>

  <a class="btn btn-primary" href="{{ path('article_table') }}">Retour à la liste</a>

  <a class="btn btn-warning" href="{{ path('article_edit', {'id': article.id}) }}">Editer l'article</a>

  {{ include('article/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/article/table.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles - Liste{% endblock %}

{% block body %}
{% include "navbar.html.twig" %}
<h1 class="text-center mb-5">Liste des articles</h1>
{% if app.user %}
<p class="p-0 m-0"></p>
{% else %}
<p class="text-center p-0 m-0"><strong>Vous n'êtes pas connecté, vous ne verrez que les articles publics</strong></p>
<p class="text-center p-0 m-0 mb-3"><a style="color:#9146FF" href="{{path('app_login')}}">Connectez-vous en cliquant ici pour voir tous les articles.</a></p>
{% endif %}
<div class="container">
  <a class="btn btn-primary mb-5" href="{{ path('default') }}">< Page d'accueil</a>
</div>
<div class="container d-flex flex-wrap justify-content-around">

  {% for article in articles %}
    {% if app.user %}
      <div class="card my-3" style="width: 30rem;">
        <img class="card-img-top" src="{{article.image ? article.image : "https://media.discordapp.net/attachments/814250385190420483/833634824140095498/no_preview.png?width=1157&height=651"}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{article.title}}</h5>
          {% if article.subtitle %}
          <h6 class="card-subtitle mb-2 text-muted">{{article.subtitle}}</h6>
          {% endif %}
        </div>
        <div class="card-body" style="overflow:auto;height:20vh;">
          <p class="card-text">{{article.content}}</p>
        </div>
        <div class="card-footer">
          <p class="card-link p-0 m-0">Public : {{ article.isPublic ? 'Oui' : 'Non' }}</p>
          <p class="card-link p-0 m-0">Date : {{ article.date ? article.date|date('Y-m-d') : 'Pas de date' }}</p>
          <p class="card-link p-0 m-0">Id article : {{ article.id }}</p>
          {% if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-warning my-2" href="{{path('article_edit', {'id': article.id})}}" class="card-link">Editer l'article</a>
            <a class="btn btn-danger" href="{{path('article_delete', {'id': article.id})}}" class="card-link">Supprimer l'article</a>
          {% endif %}
          <a class="btn btn-info" href="#" class="card-link">Poster un commentaire</a>
        </div>
      </div>
    {% else %}
      {% if article.isPublic %}
      <div class="card my-3" style="width: 30rem;">
        <img class="card-img-top" src="{{article.image ? article.image : "https://media.discordapp.net/attachments/814250385190420483/833634824140095498/no_preview.png?width=1157&height=651"}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{article.title}}</h5>
          {% if article.subtitle %}
          <h6 class="card-subtitle mb-2 text-muted">{{article.subtitle}}</h6>
          {% endif %}
        </div>
        <div class="card-body" style="overflow:auto;height:20vh;">
          <p class="card-text">{{article.content}}</p>
        </div>
        <div class="card-footer">
          <p class="card-link p-0 m-0">Public : {{ article.isPublic ? 'Oui' : 'Non' }}</p>
          <p class="card-link p-0 m-0">Date : {{ article.date ? article.date|date('Y-m-d') : 'Pas de date' }}</p>
          <p class="card-link p-0 m-0">Id article : {{ article.id }}</p>
          {% if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-warning my-2" href="{{path('article_edit', {'id': article.id})}}" class="card-link">Editer l'article</a>
            <a class="btn btn-danger" href="{{path('article_delete', {'id': article.id})}}" class="card-link">Supprimer l'article</a>
          {% endif %}
          <a class="btn btn-info" href="#" class="card-link">Poster un commentaire</a>
        </div>
      </div>
      {% endif %}
    {% endif %}

  {% else %}
  <tr>
    <td colspan="8">no records found</td>
  </tr>
  {% endfor %}
</div>
{% endblock %}